/*
 * This file is generated by jOOQ.
 */
package com.demo.productservice.jooq;


import com.demo.productservice.jooq.tables.Category;
import com.demo.productservice.jooq.tables.Databasechangeloglock;
import com.demo.productservice.jooq.tables.Product;
import com.demo.productservice.jooq.tables.records.CategoryRecord;
import com.demo.productservice.jooq.tables.records.DatabasechangeloglockRecord;
import com.demo.productservice.jooq.tables.records.ProductRecord;

import javax.annotation.Generated;

import org.jooq.ForeignKey;
import org.jooq.UniqueKey;
import org.jooq.impl.Internal;


/**
 * A class modelling foreign key relationships and constraints of tables of 
 * the <code>public</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.12.3"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

    // -------------------------------------------------------------------------
    // IDENTITY definitions
    // -------------------------------------------------------------------------


    // -------------------------------------------------------------------------
    // UNIQUE and PRIMARY KEY definitions
    // -------------------------------------------------------------------------

    public static final UniqueKey<CategoryRecord> CATEGORY_PKEY = UniqueKeys0.CATEGORY_PKEY;
    public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = UniqueKeys0.DATABASECHANGELOGLOCK_PKEY;
    public static final UniqueKey<ProductRecord> PRODUCT_PKEY = UniqueKeys0.PRODUCT_PKEY;

    // -------------------------------------------------------------------------
    // FOREIGN KEY definitions
    // -------------------------------------------------------------------------

    public static final ForeignKey<CategoryRecord, CategoryRecord> CATEGORY__FK_CATEGORY_CATEGORY_PARENT_ID = ForeignKeys0.CATEGORY__FK_CATEGORY_CATEGORY_PARENT_ID;
    public static final ForeignKey<ProductRecord, CategoryRecord> PRODUCT__FK_PRODUCT_CATEGORY_ID = ForeignKeys0.PRODUCT__FK_PRODUCT_CATEGORY_ID;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class UniqueKeys0 {
        public static final UniqueKey<CategoryRecord> CATEGORY_PKEY = Internal.createUniqueKey(Category.CATEGORY, "category_pkey", Category.CATEGORY.ID);
        public static final UniqueKey<DatabasechangeloglockRecord> DATABASECHANGELOGLOCK_PKEY = Internal.createUniqueKey(Databasechangeloglock.DATABASECHANGELOGLOCK, "databasechangeloglock_pkey", Databasechangeloglock.DATABASECHANGELOGLOCK.ID);
        public static final UniqueKey<ProductRecord> PRODUCT_PKEY = Internal.createUniqueKey(Product.PRODUCT, "product_pkey", Product.PRODUCT.ID);
    }

    private static class ForeignKeys0 {
        public static final ForeignKey<CategoryRecord, CategoryRecord> CATEGORY__FK_CATEGORY_CATEGORY_PARENT_ID = Internal.createForeignKey(Keys.CATEGORY_PKEY, Category.CATEGORY, "category__fk_category_category_parent_id", Category.CATEGORY.PARENT_ID);
        public static final ForeignKey<ProductRecord, CategoryRecord> PRODUCT__FK_PRODUCT_CATEGORY_ID = Internal.createForeignKey(Keys.CATEGORY_PKEY, Product.PRODUCT, "product__fk_product_category_id", Product.PRODUCT.CATEGORY_ID);
    }
}
